Private fields
stellarwp/telemetry pull request #101
Opened 2023-11-07 16:28 UTC by Camwyn

Don't send fields that are marked private!

2023-11-07 16:39 UTC, Camwyn commented
Context on test fatal: https://github.com/WordPress/WordPress-Coding-Standards/pull/2219

2023-11-20 09:12 UTC, lucatume requested changes

2023-11-20 09:12 UTC, lucatume commented on src/Telemetry/Data_Providers/Debug_Data.php
> +			// remove private info.
```suggestion
			// Remove private info.
```

2023-11-20 09:12 UTC, lucatume commented on src/Telemetry/Data_Providers/Debug_Data.php
> +	public function clean_private_data( $data ): array {
If you're **sure** the `$data` parameter will always be an array, then type-hint it.
If you cannot be always sure of that, add an `is_array($data)` check to bail if `$data` is not an array.

2023-11-20 09:12 UTC, lucatume commented on src/Telemetry/Data_Providers/Debug_Data.php
> +	public function clean_private_data( $data ): array {
Same applies to the return type: either you're sure of the type or not.
If you're not, remove the return type.

2023-11-20 09:12 UTC, lucatume commented on src/Telemetry/Data_Providers/Debug_Data.php
> +			);
When the data is removed, the `array_filter` function will leave "holes" in the numeric indexes.
Some code down the line might assume continuity in the indexes.
Use `array_values` to restore continuity:

```suggestion
			$details['fields'] = array_values( array_filter(
				$details['fields'],
				function ( $field ) {
					return empty( $field['private'] );
				}
			) );
```

2023-11-20 09:12 UTC, lucatume commented on src/Telemetry/Data_Providers/Debug_Data.php
> +				$details['fields'],
You're assuming `$details['fields']` will be set, check with `isset` first.

2024-02-05 15:52 UTC, tarecord approved these changes
Picking this back up. Everything looks good to me once @lucatume's suggestions are made.

Nice work @Camwyn! 🌮

2026-04-13 09:32 UTC, closed without merging