Replace Action Scheduler With Shutdown Action
stellarwp/telemetry pull request #27
Opened 2022-11-30 21:36 UTC by tarecord

This removes Action Scheduler in favor of a more lightweight implementation that hooks into the "shutdown" action for sending telemetry data.

2022-12-01 02:52 UTC, borkweb requested changes

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Last_Send_Subscriber.php
> +    public function register() {
```suggestion
	public function register() {
```

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Routes/Check.php
> +    public function get_endpoint() {
```suggestion
	public function get_endpoint() {
```

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Routes/Check.php
> +    public function action( WP_REST_Request $request ) {
```suggestion
	public function action( WP_REST_Request $request ) {
```

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Routes/Route_Subscriber.php
> +    public function register() {
```suggestion
	public function register() {
```

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Routes/Send.php
> +    public function get_endpoint() {
```suggestion
	public function get_endpoint() {
```

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Routes/Send.php
> +    public function action( WP_REST_Request $request ) {
```suggestion
	public function action( WP_REST_Request $request ) {
```

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Telemetry_Subscriber.php
> +    public function register() {
```suggestion
	public function register() {
```

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Telemetry_Subscriber.php
> +				'timeout' => 1
```suggestion
				'timeout' => 1,
```

2022-12-01 02:52 UTC, borkweb commented on src/Telemetry/Routes/Send.php
> +		$this->send_early_ok();
We want to flip these two, that way we respond with an early OK once we've validated the nonce, and then do the work to send telemetry data.

```suggestion
		$this->send_early_ok();

		Config::get_container()->get( Telemetry::class )->send_data();
```

2022-12-02 04:04 UTC, ChrisMKindred requested changes
A couple of small format items. Functionally looks great.

2022-12-02 04:04 UTC, ChrisMKindred commented on src/Telemetry/Core.php
>  		Admin_Subscriber::class,
🟠 
We should keep arrays like this in alphabetical order to make the classes easier to find in the list.

2022-12-02 04:04 UTC, ChrisMKindred commented on src/Telemetry/Telemetry.php
> +	public const AJAX_ACTION = 'stellarwp_telemetry_send_data';
🔴 
Align the equal signs
```suggestion
	public const SERVER_URL  = 'https://telemetry-api.moderntribe.qa/api/v1';
	public const AJAX_ACTION = 'stellarwp_telemetry_send_data';
```

2022-12-02 17:23 UTC, merged